name: 'Develop - GitHub Actions'

on:
  push:
    branches:
      - develop

# env:
#     tf_version: 'latest'
#     tf_working_dir: './tf-automation'
#     env: 'dev'
#     aws_region: 'ap-southeast-2'
#     artifacts_bucket: 'mamip-artifacts'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master